
import React, { useRef, useEffect, useState } from 'react';
import { WorkflowNode, Integration } from './types';
import { BusinessTemplate } from './types/advanced';
import ArchitectureGraph from './components/ArchitectureGraph';
import Dashboard from './components/Dashboard';
import { Settings as SettingsView } from './components/Settings';
import { TemplatesGallery } from './components/TemplatesGallery';
import { IntegrationsHub } from './components/IntegrationsHub';
import { ExecutionHistory } from './components/ExecutionHistory';
import { AgentThoughts } from './components/AgentThoughts';
import { Pricing } from './components/Pricing';
import RuntimeDemo from './components/RuntimeDemo';
import PRDGenerator from './components/PRDGenerator';
import IntentTester from './components/IntentTester';
import { Auth } from './components/Auth';
import { useWorkflow } from './context/WorkflowContext';
import { useAuth } from './context/AuthContext';
import {
  Bot,
  Play,
  Loader2,
  Sparkles,
  FileCode,
  Box,
  Layout,
  Terminal,
  Activity,
  Layers,
  Code2,
  Database,
  Plus,
  Trash2,
  FileText,
  Download,
  AlertCircle,
  X,
  Settings2,
  Home,
  Workflow,
  Link,
  Settings,
  CheckCircle2,
  Wand2,
  BookTemplate,
  Clock,
  Plug,
  DollarSign,
  Brain
} from 'lucide-react';

function App() {
  const { user, loading: authLoading } = useAuth();
  const {
    prompt,
    setPrompt,
    isGenerating,
    isOptimizing,
    workflow,
    selectedNode,
    setSelectedNode,
    activeTab,
    setActiveTab,
    selectedFile,
    setSelectedFile,
    executionLog,
    isSimulating,
    activeNodeId,
    generateWorkflow,
    optimizeWorkflow,
    runSimulation,
    documents,
    addDocument,
    removeDocument,
    integrations,
    toggleIntegration
  } = useWorkflow();

  // Show loading state while checking auth
  if (authLoading) {
    return (
      <div className="h-screen w-full bg-white flex items-center justify-center">
        <Loader2 size={48} className="text-slate-900 animate-spin" />
      </div>
    );
  }

  // Show auth screen if not logged in
  if (!user) {
    return <Auth />;
  }

  // Navigation State
  const [currentView, setCurrentView] = useState<'dashboard' | 'builder' | 'templates' | 'integrations' | 'history' | 'pricing' | 'runtime' | 'prd' | 'intent' | 'settings'>('dashboard');

  const logEndRef = useRef<HTMLDivElement>(null);
  
  // Local state for adding documents
  const [newDocTitle, setNewDocTitle] = useState("");
  const [newDocContent, setNewDocContent] = useState("");
  const [isAddingDoc, setIsAddingDoc] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [consoleView, setConsoleView] = useState<'console' | 'agents'>('console');

  useEffect(() => {
    if (logEndRef.current) {
        logEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [executionLog]);

  const handleAddDocument = () => {
      if(newDocTitle && newDocContent) {
          addDocument(newDocTitle, newDocContent);
          setNewDocTitle("");
          setNewDocContent("");
          setIsAddingDoc(false);
      }
  };

  const handleSelectTemplate = (template: BusinessTemplate) => {
    setPrompt(template.workflow.prompt);
    setCurrentView('builder');
    // Auto-generate after a short delay
    setTimeout(() => {
      generateWorkflow();
    }, 500);
  };

  const handleExport = async () => {
    if (!workflow) return;
    setIsExporting(true);

    try {
      // @ts-ignore
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();

      workflow.files.forEach(file => {
        zip.file(file.filename, file.content);
      });

      if (documents.length > 0) {
        const kbData = JSON.stringify(documents, null, 2);
        zip.file("knowledge_base.json", kbData);
      }

      const requirements = `langgraph
langchain
langchain-google-genai
python-dotenv
uvicorn
fastapi
`;
      zip.file("requirements.txt", requirements);

      const readme = `# ${workflow.name}

${workflow.description}

## Overview
${workflow.summary}

## AURA Automate Project
This project was generated by AURA Automate.

## Project Structure
- **main.py**: Entry point for the LangGraph workflow.
- **agents.py**: Definitions of agent behaviors and tools (Planner, Executor, etc.).
- **state.py**: Shared state definition.
${documents.length > 0 ? '- **knowledge_base.json**: Exported RAG documents.' : ''}

## Setup Instructions
1. Install Dependencies: \`pip install -r requirements.txt\`
2. Set API Key: \`export GOOGLE_API_KEY=your_key\`
3. Run: \`python main.py\`
`;
      zip.file("README.md", readme);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${workflow.name.replace(/\s+/g, '_').toLowerCase()}_aura_pkg.zip`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

    } catch (error) {
      console.error("Export failed", error);
      alert("Failed to create zip file.");
    } finally {
        setIsExporting(false);
    }
  };

  const nodeData = selectedNode?.data || {};

  return (
    <div className="h-screen w-full bg-[#030712] text-slate-200 font-sans overflow-hidden flex selection:bg-aura-500/30">
      
      {/* OS Sidebar Navigation */}
      <div className="w-16 bg-[#09090b] border-r border-slate-800 flex flex-col items-center py-6 shrink-0 z-30">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-aura-600 to-indigo-600 flex items-center justify-center text-white font-bold shadow-lg shadow-aura-600/20 mb-8 cursor-pointer" onClick={() => setCurrentView('dashboard')}>
            <Bot size={24} />
          </div>

          <div className="flex flex-col gap-4 w-full px-2">
               <NavIcon
                  icon={Home}
                  label="Dashboard"
                  isActive={currentView === 'dashboard'}
                  onClick={() => setCurrentView('dashboard')}
                />
               <NavIcon
                  icon={Workflow}
                  label="Builder"
                  isActive={currentView === 'builder'}
                  onClick={() => setCurrentView('builder')}
                />
               <NavIcon
                  icon={BookTemplate}
                  label="Templates"
                  isActive={currentView === 'templates'}
                  onClick={() => setCurrentView('templates')}
                />
               <NavIcon
                  icon={Plug}
                  label="Integrations"
                  isActive={currentView === 'integrations'}
                  onClick={() => setCurrentView('integrations')}
                />
               <NavIcon
                  icon={Clock}
                  label="History"
                  isActive={currentView === 'history'}
                  onClick={() => setCurrentView('history')}
                />
               <NavIcon
                  icon={Activity}
                  label="Runtime"
                  isActive={currentView === 'runtime'}
                  onClick={() => setCurrentView('runtime')}
                />
               <NavIcon
                  icon={FileText}
                  label="PRD Generator"
                  isActive={currentView === 'prd'}
                  onClick={() => setCurrentView('prd')}
                />
               <NavIcon
                  icon={Brain}
                  label="Intent Interpreter"
                  isActive={currentView === 'intent'}
                  onClick={() => setCurrentView('intent')}
                />
          </div>

          <div className="mt-auto flex flex-col gap-4 w-full px-2">
              <NavIcon
                  icon={DollarSign}
                  label="Pricing"
                  isActive={currentView === 'pricing'}
                  onClick={() => setCurrentView('pricing')}
                />
              <NavIcon
                  icon={Settings}
                  label="Settings"
                  isActive={currentView === 'settings'}
                  onClick={() => setCurrentView('settings')}
                />
          </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col overflow-hidden h-full">
          
          {currentView === 'dashboard' && (
              <Dashboard onCreateNew={() => setCurrentView('builder')} />
          )}

          {currentView === 'templates' && (
              <TemplatesGallery onSelectTemplate={handleSelectTemplate} />
          )}

          {currentView === 'integrations' && (
              <IntegrationsHub />
          )}

          {currentView === 'history' && (
              <ExecutionHistory />
          )}

          {currentView === 'pricing' && (
              <Pricing />
          )}

          {currentView === 'runtime' && (
              <RuntimeDemo />
          )}

          {currentView === 'prd' && (
              <PRDGenerator />
          )}

          {currentView === 'intent' && (
              <IntentTester />
          )}

          {currentView === 'settings' && (
              <SettingsView />
          )}

          {currentView === 'builder' && (
             <div className="flex-1 flex flex-col h-full overflow-hidden">
                {/* Builder Header */}
                <header className="h-14 border-b border-slate-800 bg-[#09090b] flex items-center justify-between px-4 z-20 shrink-0">
                    <div className="flex items-center gap-3">
                        <span className="font-bold text-sm text-white tracking-wide">AURA<span className="text-aura-500">Automate</span></span>
                        <div className="h-4 w-px bg-slate-800" />
                        <span className="text-xs text-slate-400 font-mono">Builder Mode</span>
                    </div>
                    
                    <div className="flex items-center gap-4">
                        {workflow && (
                            <div className="flex bg-slate-900 rounded-lg p-1 border border-slate-800 shadow-inner">
                                <button 
                                    onClick={() => setActiveTab('design')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-2 transition-all ${activeTab === 'design' ? 'bg-slate-800 text-white shadow-sm ring-1 ring-white/5' : 'text-slate-400 hover:text-white'}`}
                                >
                                    <Layers size={14} /> Design
                                </button>
                                <button 
                                    onClick={() => setActiveTab('code')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-2 transition-all ${activeTab === 'code' ? 'bg-slate-800 text-white shadow-sm ring-1 ring-white/5' : 'text-slate-400 hover:text-white'}`}
                                >
                                    <Code2 size={14} /> Code
                                </button>
                                <button 
                                    onClick={() => setActiveTab('knowledge')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-2 transition-all ${activeTab === 'knowledge' ? 'bg-slate-800 text-white shadow-sm ring-1 ring-white/5' : 'text-slate-400 hover:text-white'}`}
                                >
                                    <Database size={14} /> Knowledge
                                </button>
                            </div>
                        )}
                        {workflow && (
                            <>
                            <button 
                                onClick={optimizeWorkflow}
                                disabled={isOptimizing}
                                className="text-amber-400 hover:text-amber-300 px-3 py-1.5 rounded-md text-xs font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
                            >
                                {isOptimizing ? <Loader2 size={14} className="animate-spin"/> : <Wand2 size={14} />} 
                                Optimize Flow
                            </button>

                            <button 
                                onClick={handleExport}
                                disabled={isExporting}
                                className="bg-aura-600 hover:bg-aura-500 text-white border border-transparent px-3 py-1.5 rounded-md text-xs font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
                            >
                                {isExporting ? <Loader2 size={14} className="animate-spin"/> : <Download size={14} />} 
                                Export Package
                            </button>
                            </>
                        )}
                    </div>
                </header>

                <div className="flex-1 flex overflow-hidden">
                    {/* Left Sidebar - Prompt & Config */}
                    <div className="w-80 bg-[#0b0c10] border-r border-slate-800 flex flex-col shrink-0 z-10 shadow-xl">
                        <div className="p-4 border-b border-slate-800 bg-slate-900/20">
                            <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1">
                                <Sparkles size={10} /> AI Architect
                            </h2>
                            <textarea
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-sm text-slate-300 focus:outline-none focus:border-aura-500 focus:ring-1 focus:ring-aura-500/50 resize-none h-32 mb-3 placeholder-slate-600 transition-all font-mono leading-relaxed"
                            placeholder="Describe your automation goal..."
                            />
                            <button
                                onClick={generateWorkflow}
                                disabled={isGenerating}
                                className="w-full bg-aura-600 hover:bg-aura-500 text-white font-semibold py-2.5 rounded-md text-sm transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-aura-600/20"
                            >
                                {isGenerating ? <Loader2 className="animate-spin" size={16} /> : <Sparkles size={16} />}
                                {isGenerating ? "Architecting..." : "Generate Flow"}
                            </button>
                        </div>

                        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                            <div className="flex items-center justify-between mb-3">
                                <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Nodes Explorer</h2>
                                {workflow?.optimizationScore && (
                                    <span className="text-[10px] text-amber-500 font-mono">Score: {workflow.optimizationScore}/100</span>
                                )}
                            </div>
                            
                            {workflow ? (
                                <div className="space-y-1.5">
                                    {workflow.nodes.map(node => (
                                        <div 
                                            key={node.id} 
                                            onClick={() => setSelectedNode(node)}
                                            className={`p-2.5 rounded-md border cursor-pointer flex items-center gap-3 transition-all group ${selectedNode?.id === node.id ? 'bg-aura-500/10 border-aura-500/40' : 'bg-slate-900/40 border-slate-800 hover:border-slate-700 hover:bg-slate-800/60'}`}
                                        >
                                            <div className={`w-1.5 h-1.5 rounded-full shadow-[0_0_8px_currentColor] ${node.type === 'agent' ? 'bg-aura-500 text-aura-500' : node.type === 'router' ? 'bg-purple-500 text-purple-500' : 'bg-emerald-500 text-emerald-500'}`} />
                                            <div className="flex-1 min-w-0">
                                                <div className={`text-xs font-medium truncate group-hover:text-white ${selectedNode?.id === node.id ? 'text-aura-100' : 'text-slate-400'}`}>{node.label}</div>
                                            </div>
                                            {node.id === activeNodeId && <Activity size={12} className="text-yellow-400 animate-pulse" />}
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div className="flex flex-col items-center justify-center py-10 text-slate-700 gap-2 opacity-50">
                                    <Box size={24} />
                                    <span className="text-xs">No nodes generated</span>
                                </div>
                            )}
                        </div>

                        {/* Run Panel */}
                        {workflow && (
                            <div className="p-4 border-t border-slate-800 bg-[#0e0f12]">
                                <div className="flex items-center gap-2 mb-2">
                                    <span className="text-[10px] uppercase text-slate-500 font-bold">Simulation</span>
                                    {documents.length > 0 && (
                                        <span className="text-[10px] text-emerald-500 bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">
                                            RAG Active
                                        </span>
                                    )}
                                </div>
                                <button 
                                    onClick={runSimulation}
                                    disabled={isSimulating}
                                    className={`w-full py-3 rounded-lg font-bold text-sm flex items-center justify-center gap-2 transition-all ${
                                        isSimulating 
                                        ? 'bg-slate-800 text-slate-500 border border-slate-700' 
                                        : 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-500/20 border border-emerald-500/50'
                                    }`}
                                >
                                    {isSimulating ? <Loader2 className="animate-spin" size={16} /> : <Play size={16} fill="currentColor" />}
                                    {isSimulating ? "Running Agents..." : "Run Simulation"}
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Center Canvas / Code */}
                    <div className="flex-1 flex flex-col bg-[#131316] relative overflow-hidden">
                        
                        {!workflow && !isGenerating && (
                            <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-600 animate-in fade-in zoom-in duration-500">
                                <div className="w-24 h-24 bg-slate-900 rounded-full flex items-center justify-center mb-6 shadow-2xl ring-1 ring-slate-800">
                                    <Box size={40} className="text-slate-500" />
                                </div>
                                <h2 className="text-xl font-semibold text-slate-400 mb-2">Design Your Workflow</h2>
                                <p className="text-sm text-slate-500 max-w-md text-center px-4">
                                    Describe your process on the left. AURA agents will plan, build, and optimize the automation for you.
                                </p>
                            </div>
                        )}
                        
                        {isGenerating && (
                            <div className="absolute inset-0 flex flex-col items-center justify-center bg-[#131316]/80 backdrop-blur-sm z-50">
                                <Loader2 size={40} className="text-aura-500 animate-spin mb-4" />
                                <p className="text-slate-300 font-medium">Architecting Solution...</p>
                                <p className="text-slate-500 text-sm mt-2">Assigning Agent Roles & Writing Code</p>
                            </div>
                        )}
                         {isOptimizing && (
                            <div className="absolute inset-0 flex flex-col items-center justify-center bg-[#131316]/80 backdrop-blur-sm z-50">
                                <Wand2 size={40} className="text-amber-500 animate-pulse mb-4" />
                                <p className="text-slate-300 font-medium">Optimizing Workflow...</p>
                                <p className="text-slate-500 text-sm mt-2">Merging nodes & improving efficiency</p>
                            </div>
                        )}

                        {activeTab === 'design' && workflow && (
                            <div className="flex-1 overflow-hidden relative bg-[#0f111a]">
                                <ArchitectureGraph 
                                    nodes={workflow.nodes} 
                                    edges={workflow.edges} 
                                    activeNodeId={activeNodeId}
                                    onNodeClick={setSelectedNode}
                                />
                            </div>
                        )}

                        {activeTab === 'code' && workflow && (
                            <div className="flex-1 flex overflow-hidden">
                                <div className="w-56 bg-[#0c0c0e] border-r border-slate-800 flex flex-col">
                                    <div className="p-3 text-[10px] font-bold text-slate-500 tracking-wider">PROJECT FILES</div>
                                    {workflow.files.map(file => (
                                        <button 
                                            key={file.filename}
                                            onClick={() => setSelectedFile(file.filename)}
                                            className={`text-left px-4 py-2 text-xs font-mono flex items-center gap-2 border-l-2 transition-colors ${selectedFile === file.filename ? 'bg-slate-900 text-aura-400 border-aura-500' : 'border-transparent text-slate-400 hover:bg-slate-900 hover:text-slate-300'}`}
                                        >
                                            <FileCode size={14} className={file.filename.endsWith('.py') ? 'text-yellow-500' : 'text-slate-500'} />
                                            {file.filename}
                                        </button>
                                    ))}
                                </div>
                                <div className="flex-1 bg-[#09090b] overflow-auto p-0 flex flex-col">
                                    <div className="bg-[#09090b] border-b border-slate-800 p-2 text-xs text-slate-500 font-mono flex items-center gap-2 sticky top-0">
                                        <span className="text-yellow-500">def</span>
                                        <span className="text-slate-300">{selectedFile}</span>
                                    </div>
                                    <pre className="p-4 font-mono text-xs md:text-sm text-slate-300 leading-relaxed overflow-x-auto">
                                        <code>
                                            {workflow.files.find(f => f.filename === selectedFile)?.content}
                                        </code>
                                    </pre>
                                </div>
                            </div>
                        )}

                        {activeTab === 'knowledge' && (
                            <div className="flex-1 flex flex-col bg-[#0f111a] p-8 overflow-y-auto">
                                <div className="max-w-3xl mx-auto w-full">
                                    <div className="flex items-center justify-between mb-6">
                                        <div>
                                            <h2 className="text-xl font-bold text-slate-200">Knowledge Base</h2>
                                            <p className="text-sm text-slate-500 mt-1">Upload context for RAG (Retrieval Augmented Generation)</p>
                                        </div>
                                        <button 
                                            onClick={() => setIsAddingDoc(!isAddingDoc)}
                                            className="bg-aura-600 hover:bg-aura-500 text-white px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-2"
                                        >
                                            <Plus size={14} /> Add Document
                                        </button>
                                    </div>

                                    {isAddingDoc && (
                                        <div className="bg-slate-900 border border-slate-700 rounded-lg p-4 mb-6 animate-in fade-in slide-in-from-top-2">
                                            <input 
                                                type="text" 
                                                placeholder="Document Title" 
                                                className="w-full bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-white mb-2 focus:border-aura-500 outline-none"
                                                value={newDocTitle}
                                                onChange={(e) => setNewDocTitle(e.target.value)}
                                            />
                                            <textarea 
                                                placeholder="Paste content here (text, data, rules, etc.)"
                                                className="w-full h-32 bg-slate-950 border border-slate-800 rounded px-3 py-2 text-sm text-slate-300 mb-3 focus:border-aura-500 outline-none font-mono"
                                                value={newDocContent}
                                                onChange={(e) => setNewDocContent(e.target.value)}
                                            />
                                            <div className="flex justify-end gap-2">
                                                <button onClick={() => setIsAddingDoc(false)} className="text-slate-400 text-xs px-3 py-1.5 hover:text-white">Cancel</button>
                                                <button onClick={handleAddDocument} className="bg-aura-600 text-white text-xs px-3 py-1.5 rounded font-medium">Save to Context</button>
                                            </div>
                                        </div>
                                    )}

                                    <div className="grid gap-4">
                                        {documents.length === 0 ? (
                                            <div className="text-center py-12 border-2 border-dashed border-slate-800 rounded-xl">
                                                <Database size={32} className="mx-auto text-slate-600 mb-3" />
                                                <h3 className="text-slate-400 font-medium">Knowledge Base is Empty</h3>
                                                <p className="text-slate-600 text-sm mt-1">Add documents to enable RAG for your agents.</p>
                                            </div>
                                        ) : (
                                            documents.map(doc => (
                                                <div key={doc.id} className="bg-slate-900 border border-slate-800 rounded-lg p-4 flex gap-4 group hover:border-slate-700 transition-all">
                                                    <div className="p-2 bg-slate-800 rounded h-fit">
                                                        <FileText size={20} className="text-slate-400" />
                                                    </div>
                                                    <div className="flex-1 min-w-0">
                                                        <h3 className="font-bold text-slate-200 text-sm">{doc.title}</h3>
                                                        <div className="text-xs text-slate-500 mt-1 mb-2">Added {new Date(doc.dateAdded).toLocaleDateString()}</div>
                                                        <p className="text-slate-400 text-xs font-mono line-clamp-2">{doc.content}</p>
                                                    </div>
                                                    <button 
                                                        onClick={() => removeDocument(doc.id)}
                                                        className="text-slate-600 hover:text-red-400 self-start p-1"
                                                    >
                                                        <Trash2 size={14} />
                                                    </button>
                                                </div>
                                            ))
                                        )}
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* Bottom Panel - Console / Agent Thoughts */}
                        <div className={`h-56 bg-[#0c0c0e] border-t border-slate-800 flex flex-col shrink-0 transition-transform ${activeTab === 'knowledge' ? 'translate-y-full absolute bottom-0 w-full' : ''}`}>
                            <div className="h-9 bg-slate-950 border-b border-slate-800 flex items-center px-4 justify-between">
                                <div className="flex items-center gap-2">
                                    {/* Toggle Tabs */}
                                    <button
                                        onClick={() => setConsoleView('console')}
                                        className={`px-2 py-1 text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 rounded transition ${
                                            consoleView === 'console'
                                                ? 'bg-slate-800 text-slate-200'
                                                : 'text-slate-500 hover:text-slate-300'
                                        }`}
                                    >
                                        <Terminal size={10} /> Console
                                    </button>
                                    <button
                                        onClick={() => setConsoleView('agents')}
                                        className={`px-2 py-1 text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 rounded transition ${
                                            consoleView === 'agents'
                                                ? 'bg-slate-800 text-slate-200'
                                                : 'text-slate-500 hover:text-slate-300'
                                        }`}
                                    >
                                        <Bot size={10} /> Agent Thoughts
                                    </button>
                                </div>
                                {(isSimulating || isGenerating) && (
                                    <span className="px-2 py-0.5 rounded-full bg-emerald-950 border border-emerald-900 text-[10px] text-emerald-400 flex items-center gap-1.5">
                                        <span className="relative flex h-2 w-2">
                                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                                            <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                                        </span>
                                        Live Agent System
                                    </span>
                                )}
                            </div>

                            {/* Console View */}
                            {consoleView === 'console' && (
                                <div className="flex-1 overflow-y-auto p-3 font-mono text-xs space-y-1.5 font-medium">
                                    {executionLog.length === 0 ? (
                                        <div className="text-slate-700 italic px-2">System ready. Waiting for input...</div>
                                    ) : (
                                        executionLog.map((step, idx) => {
                                            const node = workflow?.nodes.find(n => n.id === step.nodeId);
                                            return (
                                                <div key={idx} className="flex gap-3 hover:bg-slate-900/50 p-1 rounded -mx-1 px-2 group">
                                                    <span className="text-slate-600 w-16 text-right shrink-0">{new Date(step.timestamp).toLocaleTimeString([], {hour12: false, hour:'2-digit', minute:'2-digit', second:'2-digit'})}</span>
                                                    <div className="flex flex-col gap-0.5 w-full">
                                                        <span className={`font-bold flex items-center gap-2 ${node?.type === 'agent' ? 'text-aura-400' : node?.type === 'router' ? 'text-purple-400' : 'text-emerald-400'}`}>
                                                            {node?.label || step.nodeId}
                                                        </span>
                                                        <span className="text-slate-300 leading-relaxed opacity-90 whitespace-pre-wrap">{step.output}</span>
                                                    </div>
                                                </div>
                                            );
                                        })
                                    )}
                                    <div ref={logEndRef} />
                                </div>
                            )}

                            {/* Agent Thoughts View */}
                            {consoleView === 'agents' && (
                                <div className="flex-1 overflow-hidden">
                                    <AgentThoughts executionLog={executionLog} isGenerating={isGenerating} />
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Right Sidebar - Inspector */}
                    {selectedNode && (
                        <div className="w-80 bg-[#0b0c10] border-l border-slate-800 flex flex-col shrink-0 z-20 shadow-2xl animate-in slide-in-from-right duration-300">
                            <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-900/50">
                                <h3 className="font-bold text-slate-200 text-xs uppercase tracking-wider flex items-center gap-2">
                                    <Settings2 size={12} /> Node Properties
                                </h3>
                                <button onClick={() => setSelectedNode(null)} className="text-slate-500 hover:text-white transition-colors">
                                    <X size={16} />
                                </button>
                            </div>
                            
                            <div className="p-5 flex-1 overflow-y-auto custom-scrollbar">
                                
                                {/* Identity Section */}
                                <div className="mb-6 space-y-3">
                                    <div>
                                        <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1.5">ID</label>
                                        <div className="font-mono text-xs text-slate-300 bg-slate-900 px-3 py-2 rounded border border-slate-800 select-all">
                                            {selectedNode.id}
                                        </div>
                                    </div>
                                    <div>
                                        <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1.5">Type</label>
                                        <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold border capitalize ${
                                            selectedNode.type === 'agent' ? 'bg-aura-500/10 text-aura-400 border-aura-500/20' : 
                                            selectedNode.type === 'router' ? 'bg-purple-500/10 text-purple-400 border-purple-500/20' : 
                                            selectedNode.type === 'tool' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                                            'bg-slate-800 text-slate-400 border-slate-700'
                                        }`}>
                                            {selectedNode.type === 'agent' && <Bot size={12} />}
                                            {selectedNode.type === 'tool' && <Terminal size={12} />}
                                            {selectedNode.type === 'router' && <Layout size={12} />}
                                            {selectedNode.type}
                                        </div>
                                    </div>
                                </div>

                                <div className="h-px bg-slate-800 my-4" />

                                {/* Data Properties */}
                                {!selectedNode.data ? (
                                    <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg flex items-center gap-3">
                                        <AlertCircle size={16} className="text-red-400" />
                                        <span className="text-xs text-red-300">Data object is missing</span>
                                    </div>
                                ) : (
                                    <div className="space-y-5">
                                        {/* Role */}
                                        <div>
                                            <div className="flex items-center justify-between mb-1.5">
                                                <label className="text-[10px] font-bold text-slate-500 uppercase">Role</label>
                                                {!nodeData.role && <span className="text-[9px] text-amber-500 flex items-center gap-1"><AlertCircle size={8} /> Missing</span>}
                                            </div>
                                            <div className={`text-sm p-3 rounded-lg border ${nodeData.role ? 'bg-slate-900 border-slate-800 text-slate-300' : 'bg-slate-900/30 border-slate-800/50 text-slate-600 italic'}`}>
                                                {nodeData.role || "No role assigned"}
                                            </div>
                                        </div>

                                        {/* Goal */}
                                        <div>
                                            <div className="flex items-center justify-between mb-1.5">
                                                <label className="text-[10px] font-bold text-slate-500 uppercase">Goal</label>
                                                {!nodeData.goal && <span className="text-[9px] text-amber-500 flex items-center gap-1"><AlertCircle size={8} /> Missing</span>}
                                            </div>
                                            <div className={`text-sm p-3 rounded-lg border ${nodeData.goal ? 'bg-slate-900 border-slate-800 text-slate-300' : 'bg-slate-900/30 border-slate-800/50 text-slate-600 italic'}`}>
                                                {nodeData.goal || "No goal defined"}
                                            </div>
                                        </div>

                                        {/* Description */}
                                        <div>
                                            <div className="flex items-center justify-between mb-1.5">
                                                <label className="text-[10px] font-bold text-slate-500 uppercase">Description</label>
                                                {!nodeData.description && <span className="text-[9px] text-amber-500 flex items-center gap-1"><AlertCircle size={8} /> Missing</span>}
                                            </div>
                                            <div className={`text-sm p-3 rounded-lg border ${nodeData.description ? 'bg-slate-900 border-slate-800 text-slate-300' : 'bg-slate-900/30 border-slate-800/50 text-slate-600 italic'}`}>
                                                {nodeData.description || "No description provided"}
                                            </div>
                                        </div>

                                        {/* Tools */}
                                        <div>
                                            <div className="flex items-center justify-between mb-1.5">
                                                <label className="text-[10px] font-bold text-slate-500 uppercase">Tools</label>
                                                {(!nodeData.tools || nodeData.tools.length === 0) && <span className="text-[9px] text-slate-600">None</span>}
                                            </div>
                                            {nodeData.tools && nodeData.tools.length > 0 ? (
                                                <div className="flex flex-wrap gap-2">
                                                    {nodeData.tools.map((tool: string, i: number) => (
                                                        <div key={i} className="px-2.5 py-1.5 bg-slate-800 border border-slate-700 rounded text-xs text-blue-300 font-mono flex items-center gap-2">
                                                            <Terminal size={10} className="text-slate-500" />
                                                            {tool}
                                                        </div>
                                                    ))}
                                                </div>
                                            ) : (
                                                <div className="p-3 border border-dashed border-slate-800 rounded text-xs text-slate-600 italic text-center">
                                                    No tools configured
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </div>
            </div>
          )}
      </div>
    </div>
  );
}

const NavIcon = ({ icon: Icon, label, isActive, onClick }: { icon: any, label: string, isActive: boolean, onClick: () => void }) => (
    <button 
        onClick={onClick}
        className={`w-full h-10 rounded-lg flex items-center justify-center transition-all group relative ${isActive ? 'bg-slate-800 text-aura-400' : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/50'}`}
    >
        <Icon size={20} strokeWidth={isActive ? 2.5 : 2} />
        {/* Tooltip */}
        <span className="absolute left-14 bg-slate-800 text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-50 border border-slate-700 font-medium">
            {label}
        </span>
    </button>
)

export default App;
