/**
 * Plan Visualizer Component
 *
 * Displays the execution plan generated by the Intent Engine
 * Shows: goal, steps, dependencies, agents, tools, estimated time
 * Allows users to review before execution
 */

import React from 'react';
import { Brain, Clock, Users, Wrench, CheckCircle2, ArrowRight, Play, Edit2, RefreshCw, AlertTriangle } from 'lucide-react';

export interface TaskStep {
  id: string;
  description: string;
  agent: string;
  tools: string[];
  estimatedTime: number;
  dependencies: string[];
  status?: 'pending' | 'running' | 'completed' | 'failed';
}

export interface TaskPlan {
  goal: {
    intent: string;
    domain: string;
    deliverables: string[];
  };
  steps: TaskStep[];
  dependencies: Array<{ from: string; to: string }>;
  estimatedTotalTime: number;
  requiredAgents: string[];
  requiredTools: string[];
  confidence?: number;
}

interface PlanVisualizerProps {
  plan: TaskPlan | null;
  onExecute: () => void;
  onEdit: (editPrompt: string) => void;
  onRegenerate: () => void;
  isExecuting?: boolean;
}

const agentColors: { [key: string]: string } = {
  'research': 'from-indigo-600 to-blue-600',
  'prd_writer': 'from-blue-600 to-cyan-600',
  'analyst': 'from-emerald-600 to-teal-600',
  'jira_manager': 'from-amber-600 to-orange-600',
  'ux_writer': 'from-purple-600 to-pink-600',
  'planner': 'from-violet-600 to-purple-600',
  'executor': 'from-green-600 to-emerald-600'
};

const agentIcons: { [key: string]: string } = {
  'research': '🔍',
  'prd_writer': '📄',
  'analyst': '📊',
  'jira_manager': '✓',
  'ux_writer': '✍️',
  'planner': '🗺️',
  'executor': '⚡'
};

export const PlanVisualizer: React.FC<PlanVisualizerProps> = ({
  plan,
  onExecute,
  onEdit,
  onRegenerate,
  isExecuting = false
}) => {
  const [editMode, setEditMode] = React.useState(false);
  const [editPrompt, setEditPrompt] = React.useState('');

  if (!plan) {
    return (
      <div className="bg-[#0f111a] border border-slate-800 rounded-xl p-8 text-center">
        <Brain size={48} className="mx-auto text-slate-600 mb-4" />
        <h3 className="text-slate-400 font-medium mb-2">No Plan Generated</h3>
        <p className="text-slate-600 text-sm">Describe your goal to generate an execution plan</p>
      </div>
    );
  }

  const handleEdit = () => {
    if (editPrompt.trim()) {
      onEdit(editPrompt);
      setEditMode(false);
      setEditPrompt('');
    }
  };

  const formatTime = (seconds: number): string => {
    if (seconds < 60) return `${seconds}s`;
    const minutes = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return secs > 0 ? `${minutes}m ${secs}s` : `${minutes}m`;
  };

  return (
    <div className="bg-[#0f111a] border border-slate-800 rounded-xl overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-aura-600/10 to-indigo-600/10 border-b border-slate-800 p-5">
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-start gap-3 flex-1">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-aura-600 to-indigo-600 flex items-center justify-center shadow-lg shrink-0">
              <Brain size={24} className="text-white" />
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-bold text-white text-lg mb-1">Execution Plan</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{plan.goal.intent}</p>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-xs text-slate-500 flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-aura-500"></span>
                  Domain: <span className="text-slate-400 font-medium capitalize">{plan.goal.domain}</span>
                </span>
                {plan.confidence && (
                  <span className="text-xs text-slate-500 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                    Confidence: <span className="text-emerald-400 font-medium">{Math.round(plan.confidence * 100)}%</span>
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 shrink-0 ml-4">
            <button
              onClick={() => setEditMode(!editMode)}
              className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
              title="Edit Plan"
            >
              <Edit2 size={16} />
            </button>
            <button
              onClick={onRegenerate}
              disabled={isExecuting}
              className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors disabled:opacity-50"
              title="Regenerate Plan"
            >
              <RefreshCw size={16} />
            </button>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-4 gap-3 mt-4">
          <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-3">
            <div className="flex items-center gap-2 mb-1">
              <CheckCircle2 size={14} className="text-blue-400" />
              <span className="text-[10px] text-slate-500 uppercase font-bold">Steps</span>
            </div>
            <div className="text-xl font-bold text-white">{plan.steps.length}</div>
          </div>
          <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-3">
            <div className="flex items-center gap-2 mb-1">
              <Clock size={14} className="text-emerald-400" />
              <span className="text-[10px] text-slate-500 uppercase font-bold">Time</span>
            </div>
            <div className="text-xl font-bold text-white">{formatTime(plan.estimatedTotalTime)}</div>
          </div>
          <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-3">
            <div className="flex items-center gap-2 mb-1">
              <Users size={14} className="text-purple-400" />
              <span className="text-[10px] text-slate-500 uppercase font-bold">Agents</span>
            </div>
            <div className="text-xl font-bold text-white">{plan.requiredAgents.length}</div>
          </div>
          <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-3">
            <div className="flex items-center gap-2 mb-1">
              <Wrench size={14} className="text-amber-400" />
              <span className="text-[10px] text-slate-500 uppercase font-bold">Tools</span>
            </div>
            <div className="text-xl font-bold text-white">{plan.requiredTools.length}</div>
          </div>
        </div>
      </div>

      {/* Edit Mode */}
      {editMode && (
        <div className="bg-slate-900/30 border-b border-slate-800 p-4">
          <label className="text-xs text-slate-400 mb-2 block">Edit Plan (Natural Language):</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={editPrompt}
              onChange={(e) => setEditPrompt(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleEdit()}
              placeholder='e.g., "Add a step to validate data" or "Remove the notification step"'
              className="flex-1 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:border-aura-500 focus:ring-1 focus:ring-aura-500/50"
            />
            <button
              onClick={handleEdit}
              disabled={!editPrompt.trim()}
              className="bg-aura-600 hover:bg-aura-500 disabled:bg-slate-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
            >
              Apply
            </button>
            <button
              onClick={() => {
                setEditMode(false);
                setEditPrompt('');
              }}
              className="text-slate-400 hover:text-white px-3 py-2 text-sm"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Steps Timeline */}
      <div className="p-5">
        <h4 className="text-xs font-bold text-slate-500 uppercase mb-4">Execution Steps</h4>
        <div className="space-y-3">
          {plan.steps.map((step, index) => {
            const agentColor = agentColors[step.agent] || 'from-slate-600 to-slate-700';
            const agentIcon = agentIcons[step.agent] || '🤖';
            const hasDependencies = step.dependencies.length > 0;

            return (
              <div key={step.id} className="group">
                <div className="flex gap-4">
                  {/* Step Number & Connection Line */}
                  <div className="flex flex-col items-center shrink-0">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-slate-800 to-slate-900 border-2 border-slate-700 flex items-center justify-center text-xs font-bold text-slate-400 group-hover:border-aura-500 transition-colors">
                      {index + 1}
                    </div>
                    {index < plan.steps.length - 1 && (
                      <div className="w-px h-full bg-slate-800 mt-2"></div>
                    )}
                  </div>

                  {/* Step Card */}
                  <div className="flex-1 pb-4">
                    <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-4 hover:border-slate-700 transition-all group-hover:bg-slate-900 cursor-pointer">
                      {/* Agent Badge & Time */}
                      <div className="flex items-center justify-between mb-2">
                        <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-lg bg-gradient-to-r ${agentColor} text-white text-xs font-bold`}>
                          <span>{agentIcon}</span>
                          <span className="capitalize">{step.agent.replace('_', ' ')}</span>
                        </div>
                        <span className="text-xs text-slate-500 flex items-center gap-1">
                          <Clock size={12} /> {formatTime(step.estimatedTime)}
                        </span>
                      </div>

                      {/* Description */}
                      <p className="text-sm text-slate-300 leading-relaxed mb-3">
                        {step.description}
                      </p>

                      {/* Tools & Dependencies */}
                      <div className="flex items-center gap-4 flex-wrap">
                        {step.tools.length > 0 && (
                          <div className="flex items-center gap-1.5">
                            <Wrench size={12} className="text-slate-600" />
                            <div className="flex gap-1">
                              {step.tools.map((tool, i) => (
                                <span
                                  key={i}
                                  className="text-[10px] px-2 py-0.5 bg-slate-800 border border-slate-700 rounded text-blue-300 font-mono"
                                >
                                  {tool}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}
                        {hasDependencies && (
                          <div className="flex items-center gap-1.5">
                            <AlertTriangle size={12} className="text-amber-500" />
                            <span className="text-[10px] text-amber-400">
                              Depends on step {step.dependencies.join(', ')}
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Deliverables */}
      {plan.goal.deliverables && plan.goal.deliverables.length > 0 && (
        <div className="border-t border-slate-800 p-5 bg-slate-900/20">
          <h4 className="text-xs font-bold text-slate-500 uppercase mb-3">Expected Deliverables</h4>
          <div className="grid grid-cols-2 gap-2">
            {plan.goal.deliverables.map((deliverable, i) => (
              <div key={i} className="flex items-center gap-2 text-sm text-slate-400">
                <CheckCircle2 size={14} className="text-emerald-500 shrink-0" />
                <span>{deliverable}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Execute Button */}
      <div className="border-t border-slate-800 p-5 bg-slate-900/30">
        <button
          onClick={onExecute}
          disabled={isExecuting}
          className={`w-full py-4 rounded-xl font-bold text-sm flex items-center justify-center gap-3 transition-all shadow-lg ${
            isExecuting
              ? 'bg-slate-800 text-slate-500 cursor-not-allowed'
              : 'bg-gradient-to-r from-aura-600 to-indigo-600 hover:from-aura-500 hover:to-indigo-500 text-white shadow-aura-600/30'
          }`}
        >
          {isExecuting ? (
            <>
              <div className="w-4 h-4 border-2 border-slate-600 border-t-slate-400 rounded-full animate-spin" />
              Executing Plan...
            </>
          ) : (
            <>
              <Play size={18} fill="currentColor" />
              Execute Plan
              <ArrowRight size={18} />
            </>
          )}
        </button>
      </div>
    </div>
  );
};
